# Generated by Django 2.2 on 2021-11-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scRealtorApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='added_by',
        ),
    ]
